CREATE TABLE permissao (
    id            BIGINT(3)   PRIMARY KEY AUTO_INCREMENT,
    nome          VARCHAR(50) NOT NULL,
    permissao_id  BIGINT(3),
    FOREIGN KEY (permissao_id) REFERENCES permissao(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO permissao (nome) VALUES ('ROLE_CADASTRAR_USUARIO');
INSERT INTO permissao (nome) VALUES ('ROLE_ALTERAR_USUARIO');
INSERT INTO permissao (nome) VALUES ('ROLE_EXCLUIR_USUARIO');
INSERT INTO permissao (nome) VALUES ('ROLE_CONSULTAR_USUARIO');
INSERT INTO permissao (nome) VALUES ('ROLE_CONVIDAR_USUARIO');
INSERT INTO permissao (nome) VALUES ('ROLE_ATIVAR_DESATIVAR_USUARIO');
INSERT INTO permissao (nome) VALUES ('ROLE_CADASTRAR_PERFIL');
INSERT INTO permissao (nome) VALUES ('ROLE_ALTERAR_PERFIL');
INSERT INTO permissao (nome) VALUES ('ROLE_EXCLUIR_PERFIL');
INSERT INTO permissao (nome) VALUES ('ROLE_CONSULTAR_PERFIL');
